# Whenever a tag of the form #.xxxx is pushed against master, generate a
# draft release and upload the ZIP and JSON file to it.  Maintainers then
# will manually add the changelist and publish it.

name: Props3D Dredd Lawgiver CI - Build Draft Release

on:
  push:
    branches:
      - "main"
    tags:
      # Run for tags of the x.x.x* form (i.e. 3.0.0, 3.0.0-beta, etc.).
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build-firmware:
    uses: ./.github/workflows/build-firmware.yml
    secrets: inherit # pass all secrets

  tag-to-draft-release:
    name: Create Draft Release
    needs: build-firmware
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: firmware-builds
          pattern: dredd-lawgiver-*
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R

      - name: Tag and Upload Draft Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.ref_name }}"
          prerelease: true
          title: "${{ github.ref_name }} Release"
          files: |
            firmware-builds/**/*.hex
